# Ejemplo de Makefile en server/Makefile

# Objetivo por defecto
all: server

# Regla que compila el ejecutable "server"
server:
	g++ -Wall -o src/server \
	    src/main.cpp \
	    src/Server.cpp \
	    src/Message.cpp \
	    src/User.cpp \
	    src/WebSocket.cpp \
